# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yuri Turov
email: why.turov@gmail.com
description: >
  Yuri Turov iOS Apps
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yuriturov.com" # the base hostname & protocol for your site
twitter: YuriTurov

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
